<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="LibVLCSharp" Version="[3.10.0]" />
    <PackageVersion Include="VideoLAN.LibVLC.Windows" Version="[3.0.23.1]" />
    <PackageVersion Include="BouncyCastle.Cryptography" Version="[2.6.2]" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="[10.0.0]" />
    <PackageVersion Include="Avalonia.Headless" Version="[12.1.2]" />
    <PackageVersion Include="Avalonia.Skia" Version="[12.1.2]" />
    <PackageVersion Include="Flurl.Http" Version="[4.0.2]" />
    <PackageVersion Include="QRCoder" Version="[1.8.0]" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="[10.0.0]" />
    <PackageVersion Include="Microsoft.Extensions.TimeProvider.Testing" Version="[10.0.0]" />
    <PackageVersion Include="Avalonia.Desktop" Version="[12.1.2]" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="[8.4.2]" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="[18.8.1]" />
    <PackageVersion Include="MyAvaloniaManagement.Plugin.Build" Version="[3.4.1]" />
    <PackageVersion Include="MyAvaloniaManagement.PluginSdk" Version="[3.4.1]" />
    <PackageVersion Include="MyAvaloniaManagement.Icons" Version="[3.4.1]" />
    <PackageVersion Include="MyAvaloniaManagement.PluginSdk.UI" Version="[3.4.1]" />
    <PackageVersion Include="xunit" Version="[2.9.3]" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="[3.1.5]" />
  </ItemGroup>
</Project>
