<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusicNetEasePlugin.Plugin\MusicNetEasePlugin.Plugin.csproj" />
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

</Project>
